"""add message media metadata

Revision ID: 06099be6f519
Revises: 95120147d5e1
Create Date: 2026-08-26 22:26:11.560794
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '06099be6f519'
down_revision: str | Sequence[str] | None = '95120147d5e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_id', sa.String(length=160), nullable=True))
    op.add_column('messages', sa.Column('media_url', sa.String(length=2000), nullable=True))
    op.add_column('messages', sa.Column('media_mime_type', sa.String(length=160), nullable=True))
    op.add_column('messages', sa.Column('media_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'media_filename')
    op.drop_column('messages', 'media_mime_type')
    op.drop_column('messages', 'media_url')
    op.drop_column('messages', 'media_id')
    # ### end Alembic commands ###
