"""add whatsapp templates and service window

Revision ID: 2b175c966223
Revises: 06099be6f519
Create Date: 2026-08-27 08:20:35.856617
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2b175c966223'
down_revision: str | Sequence[str] | None = '06099be6f519'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PAUSED', name='whatsapptemplatestatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_whatsapp_templates_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_account_id'], ['whatsapp_accounts.id'], name=op.f('fk_whatsapp_templates_whatsapp_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_templates')),
    sa.UniqueConstraint('whatsapp_account_id', 'name', 'language', name=op.f('uq_whatsapp_templates_whatsapp_account_id'))
    )
    op.create_index(op.f('ix_whatsapp_templates_organization_id'), 'whatsapp_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_whatsapp_account_id'), 'whatsapp_templates', ['whatsapp_account_id'], unique=False)
    op.add_column('conversations', sa.Column('last_customer_message_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('template_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_messages_template_id'), 'messages', ['template_id'], unique=False)
    op.create_foreign_key(op.f('fk_messages_template_id_whatsapp_templates'), 'messages', 'whatsapp_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_messages_template_id_whatsapp_templates'), 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_template_id'), table_name='messages')
    op.drop_column('messages', 'template_id')
    op.drop_column('conversations', 'last_customer_message_at')
    op.drop_index(op.f('ix_whatsapp_templates_whatsapp_account_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_organization_id'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    # ### end Alembic commands ###
