"""add configurable automations

Revision ID: 3fe79405433e
Revises: 2b175c966223
Create Date: 2026-08-27 08:33:28.622481
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3fe79405433e'
down_revision: str | Sequence[str] | None = '2b175c966223'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='automationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trigger_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_automations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automations')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_automations_organization_id'))
    )
    op.create_index(op.f('ix_automations_organization_id'), 'automations', ['organization_id'], unique=False)
    op.create_table('automation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('automation_id', sa.UUID(), nullable=False),
    sa.Column('automation_version', sa.Integer(), nullable=False),
    sa.Column('current_node_id', sa.String(length=100), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], name=op.f('fk_automation_sessions_automation_id_automations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_automation_sessions_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_automation_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_sessions')),
    sa.UniqueConstraint('conversation_id', name=op.f('uq_automation_sessions_conversation_id'))
    )
    op.create_index(op.f('ix_automation_sessions_automation_id'), 'automation_sessions', ['automation_id'], unique=False)
    op.create_index(op.f('ix_automation_sessions_organization_id'), 'automation_sessions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_sessions_organization_id'), table_name='automation_sessions')
    op.drop_index(op.f('ix_automation_sessions_automation_id'), table_name='automation_sessions')
    op.drop_table('automation_sessions')
    op.drop_index(op.f('ix_automations_organization_id'), table_name='automations')
    op.drop_table('automations')
    # ### end Alembic commands ###
