"""add organization profile and global user email

Revision ID: 6c54112436ae
Revises: 3003cfa72354
Create Date: 2026-08-26 20:25:50.604828
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6c54112436ae'
down_revision: str | Sequence[str] | None = '3003cfa72354'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('opening_hours', sa.String(length=500), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=False),
    sa.Column('primary_color', sa.String(length=16), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_profiles')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_organization_profiles_organization_id'))
    )
    op.drop_constraint(op.f('uq_users_organization_id'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_organization_id'), 'users', ['organization_id', 'email'], postgresql_nulls_not_distinct=False)
    op.drop_table('organization_profiles')
    # ### end Alembic commands ###
