"""add ai confidence controls

Revision ID: 8d1d1e63d5d3
Revises: b5064a90de07
Create Date: 2026-08-27 11:21:04.942530
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8d1d1e63d5d3'
down_revision: str | Sequence[str] | None = 'b5064a90de07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_configurations', sa.Column('minimum_confidence', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_ai_runs_input_message_id'), 'ai_runs', ['input_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ai_runs_input_message_id'), 'ai_runs', type_='unique')
    op.drop_column('ai_configurations', 'minimum_confidence')
    # ### end Alembic commands ###
