"""add ai learning foundation

Revision ID: b5064a90de07
Revises: df122733301e
Create Date: 2026-08-27 11:09:46.885051
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b5064a90de07'
down_revision: str | Sequence[str] | None = 'df122733301e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('tone', sa.String(length=40), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('fallback_message', sa.Text(), nullable=False),
    sa.Column('history_message_limit', sa.Integer(), nullable=False),
    sa.Column('retrieval_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_configurations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_configurations')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_ai_configurations_organization_id'))
    )
    op.create_table('ai_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('input_message_id', sa.UUID(), nullable=False),
    sa.Column('output_message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'ESCALATED', name='airunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_ai_runs_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['input_message_id'], ['messages.id'], name=op.f('fk_ai_runs_input_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_message_id'], ['messages.id'], name=op.f('fk_ai_runs_output_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runs'))
    )
    op.create_index(op.f('ix_ai_runs_conversation_id'), 'ai_runs', ['conversation_id'], unique=False)
    op.create_index('ix_ai_runs_organization_created', 'ai_runs', ['organization_id', 'created_at'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Enum('HELPFUL', 'UNHELPFUL', name='aifeedbackrating', native_enum=False, length=20), nullable=False),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], name=op.f('fk_ai_feedback_ai_run_id_ai_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_feedback_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback')),
    sa.UniqueConstraint('ai_run_id', 'user_id', name=op.f('uq_ai_feedback_ai_run_id'))
    )
    op.create_index(op.f('ix_ai_feedback_ai_run_id'), 'ai_feedback', ['ai_run_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_organization_id'), 'ai_feedback', ['organization_id'], unique=False)
    op.create_table('knowledge_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='knowledgesuggestionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], name=op.f('fk_knowledge_suggestions_ai_run_id_ai_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_knowledge_suggestions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_knowledge_suggestions_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_suggestions'))
    )
    op.create_index(op.f('ix_knowledge_suggestions_ai_run_id'), 'knowledge_suggestions', ['ai_run_id'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_organization_id'), 'knowledge_suggestions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_suggestions_organization_id'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_ai_run_id'), table_name='knowledge_suggestions')
    op.drop_table('knowledge_suggestions')
    op.drop_index(op.f('ix_ai_feedback_organization_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_ai_run_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index('ix_ai_runs_organization_created', table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_conversation_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_table('ai_configurations')
    # ### end Alembic commands ###
